add_requires("libsdl")
add_requires("libsdl_image")
add_requires("libsdl_ttf")
add_requires("libsdl_gfx")
add_rules("plugin.vsxmake.autoupdate")

target("Snake")
  set_rundir(".")
  set_kind("binary")
  set_languages("c++20")
  add_files("src/*.cpp")
  add_headerfiles("src/*.hpp")
  add_installfiles("res/arial.ttf", {prefixdir = "bin/res"})
  add_packages("libsdl")
  add_packages("libsdl_image")
  add_packages("libsdl_ttf")
  add_packages("libsdl_gfx")